LARGE_CAP_TICKERS = [
"RELIANCE.NS","TCS.NS","HDFCBANK.NS","INFY.NS","ICICIBANK.NS","HINDUNILVR.NS",
"SBIN.NS","LT.NS","AXISBANK.NS","BAJFINANCE.NS","KOTAKBANK.NS","ITC.NS",
"BHARTIARTL.NS","MARUTI.NS","SUNPHARMA.NS","WIPRO.NS","HCLTECH.NS","M&M.NS",
"NTPC.NS","POWERGRID.NS","TATAMOTORS.NS","ULTRACEMCO.NS","ADANIPORTS.NS",
"CIPLA.NS","DRREDDY.NS","NESTLEIND.NS","BAJAJFINSV.NS","DIVISLAB.NS","JSWSTEEL.NS",
"TATASTEEL.NS","COALINDIA.NS","GRASIM.NS","HDFCLIFE.NS","TECHM.NS","UPL.NS",
"BRITANNIA.NS","EICHERMOT.NS","HINDALCO.NS","ONGC.NS","BPCL.NS","APOLLOHOSP.NS",
"HEROMOTOCO.NS","SBILIFE.NS","ADANIENT.NS","BAJAJ-AUTO.NS","INDUSINDBK.NS",
"ICICILOMBARD.NS","TATACONSUM.NS","ASIANPAINT.NS","SHREECEM.NS","DABUR.NS",
"PIDILITIND.NS","GODREJCP.NS","HAVELLS.NS","TORNTPHARM.NS","COLPAL.NS",
"BERGEPAINT.NS","DLF.NS","ZEEL.NS","CHOLAFIN.NS","MPHASIS.NS","MINDTREE.NS",
"GAIL.NS","IOC.NS","PETRONET.NS","REC.NS","PNBHOUSING.NS","BANKBARODA.NS",
"FEDERALBNK.NS","IDFCFIRSTB.NS","GLAND.NS","ALKEM.NS","MAXHEALTH.NS",
"ICICIPRULI.NS","ABB.NS","SIEMENS.NS","CUMMINSIND.NS","BHEL.NS","ASHOKLEY.NS",
"CONCOR.NS","IRCTC.NS","LICHSGFIN.NS","SRF.NS","ADANIGREEN.NS","ADANITRANS.NS",
"ADANIGAS.NS"
]

MID_CAP_TICKERS = [
"MANKIND.NS","AUROPHARMA.NS","CANBK.NS","LTFH.NS","GMRINFRA.NS","GUJGAZ.NS",
"INDIGO.NS","PAGEIND.NS","DIXON.NS","POLYCAB.NS","VOLTAS.NS","TVSMOTOR.NS",
"BALKRISIND.NS","CROMPTON.NS","BIOCON.NS","MAXFINANCIAL.NS","ICICISEC.NS",
"PERSISTENT.NS","MUTHOOTFIN.NS","ASTRAL.NS","JUBILANT.NS","PIIND.NS",
"TATAELXSI.NS","COROMANDEL.NS","MANAPPURAM.NS","ADITYABIRLA.NS","ALEMBIC.NS",
"BATAINDIA.NS","LTIM.NS","GODREJPROP.NS","DEEPAKNTR.NS","SUPREMEIND.NS",
"THERMAX.NS","RBLBANK.NS","SUNDARMFIN.NS","SHRIRAMFIN.NS","LAURUSLABS.NS",
"UBL.NS","JSWENERGY.NS","IEX.NS","ZYDUSLIFE.NS","KEI.NS","BLUESTARCO.NS",
"TRENT.NS","ADANIWIL.NS","ADANIPOWER.NS","GUJFLUORO.NS","CASTROLIND.NS",
"INDHOTEL.NS","RADICO.NS","APLAPOLLO.NS","RELAXO.NS","FINEORG.NS",
"HATSUN.NS","PRESTIGE.NS","OBEROIRLTY.NS","VARUNBEV.NS","EMAMILTD.NS",
"IGL.NS","KAJARIACER.NS","RITES.NS","SKFINDIA.NS","HAL.NS","CESC.NS",
"ENDURANCE.NS","GRINDWELL.NS","GNFC.NS","NAVINFLUOR.NS","LINDEINDIA.NS",
"AIAENG.NS","KANSAINER.NS","BIRLASOFT.NS","COFORGE.NS","SYNGENE.NS",
"NARAYANA.NS","FORTIS.NS","PVR.NS","INOXLEISUR.NS","SPANDANA.NS","CUB.NS",
"KVB.NS","SOUTHBANK.NS"
]

SMALL_CAP_TICKERS = [
"GOFORTHPHIL.NS","DELHIVERY.NS","ASTERDM.NS","PIRAMALPHAR.NS","APTUS.NS",
"CSCCL.NS","CITYUNION.NS","PNCINFRA.NS","TATACHEM.NS","HINDCOPPER.NS",
"BEML.NS","GRSE.NS","SCHNEIDER.NS","GMDC.NS","CRAG.NS","CRAFTSMAN.NS",
"SCHAFFLER.NS","MAZDOCK.NS","COCHIN.NS","GARDENREACH.NS","RVNL.NS","IRCON.NS",
"IRFC.NS","HUDCO.NS","ENGINERSIND.NS","NBCC.NS","TANLA.NS","ROUTE.NS",
"SUBEX.NS","INTELLECT.NS","HFCL.NS","TEJASNET.NS","STERLITE.NS",
"DEEPAKFERT.NS","BALRAMCHIN.NS","DHAMPURSUG.NS","EIDPARRY.NS","AVANTIFEED.NS",
"VENKY.NS","KRBL.NS","SOMANYCERA.NS","ORIENTCEM.NS","INDIACEM.NS",
"HEIDELBERG.NS","JINDALSAW.NS","WELSPUNCORP.NS","RATNAMANI.NS","FINOLEXCAB.NS",
"BOROSIL.NS","SWSOLAR.NS","INOXWIND.NS","INDIAGLYCO.NS","GUJALKALI.NS",
"DCW.NS","THIRUMALAI.NS","RUCHIRA.NS","JKPAPER.NS","WESTCOAST.NS","DISHMAN.NS",
"SEQUENT.NS","CAPLIPOINT.NS","GRANULES.NS","NATCO.NS","NEULAND.NS",
"WELSPUNIND.NS","RAYMOND.NS","ARVIND.NS","FLFL.NS","HIMADRI.NS",
"ORIENTCARB.NS","PNBGILTS.NS","UJJIVANSFB.NS","EQUITAS.NS","CSBBANK.NS",
"DCBBANK.NS","REPCOHOME.NS","YESBANK.NS","BANDHANBNK.NS","PNB.NS",
"UNIONBANK.NS","BANKINDIA.NS","INDIANBANK.NS","CENTRALBK.NS","UCOBANK.NS",
"IOB.NS","PNBSIND.NS","IDBI.NS","AUBANK.NS","EQUITASBNK.NS","JKBANK.NS",
"KARNATKABANK.NS","RATNABANK.NS","TMB.NS","ESAFSFB.NS","FSFB.NS","NSFB.NS",
"SURYODAYBANK.NS","JANA.SFB.NS","UTKARSHBANK.NS","SHIVALIKBANK.NS",
"PAYTMPAYBANK.NS","AIRTELPBANK.NS","INDIAPOSTPB.NS","YESPBANK.NS",
"UTIBK.NS","PSBINDIABANK.NS","MAHABANK.NS","IOPBANK.NS","ORIENTBANK.NS"
]


SECTORS = {
    "CLUSTER_1": [  # High correlation cluster (mostly banks)
        "HDFCBANK.NS","ICICIBANK.NS","SBIN.NS","KOTAKBANK.NS","AXISBANK.NS",
        "INDUSINDBK.NS","YESBANK.NS","IDFCFIRSTB.NS","FEDERALBNK.NS","RBLBANK.NS",
        "BANDHANBNK.NS","PNB.NS","BANKBARODA.NS","UNIONBANK.NS","BANKINDIA.NS",
        "INDIANBANK.NS","CANBK.NS","CENTRALBK.NS","UCOBANK.NS","IOB.NS",
        "PNBSIND.NS","IDBI.NS","CSBBANK.NS","AUBANK.NS","EQUITASBNK.NS",
        "UJJIVANSFB.NS","JKBANK.NS","KVB.NS","KARNATKABANK.NS","DCBBANK.NS",
        "CUB.NS","SOUTHBANK.NS","RATNABANK.NS","TMB.NS","ESAFSFB.NS",
        "FSFB.NS","NSFB.NS","SURYODAYBANK.NS","JANA.SFB.NS","UTKARSHBANK.NS",
        "SHIVALIKBANK.NS","PAYTMPAYBANK.NS","AIRTELPBANK.NS","INDIAPOSTPB.NS",
        "YESPBANK.NS","UTIBK.NS","PSBINDIABANK.NS","MAHABANK.NS","IOPBANK.NS",
        "ORIENTBANK.NS"
    ],

    "CLUSTER_2": [  # IT / Tech correlation cluster
        "TCS.NS","INFY.NS","WIPRO.NS","HCLTECH.NS","TECHM.NS",
        "LTIM.NS","PERSISTENT.NS","COFORGE.NS","MPHASIS.NS","MINDTREE.NS",
        "BIRLASOFT.NS","TATAELXSI.NS","SUBEX.NS","INTELLECT.NS","ROUTE.NS","TANLA.NS",
        "DIXON.NS","LTIM.NS","COFORGE.NS","PERSISTENT.NS"
    ],

    "CLUSTER_3": [  # Pharma & healthcare
        "SUNPHARMA.NS","CIPLA.NS","DRREDDY.NS","DIVISLAB.NS","AUROPHARMA.NS",
        "BIOCON.NS","ALKEM.NS","GLAND.NS","LAURUSLABS.NS","TORNTPHARM.NS",
        "NATCO.NS","GRANULES.NS","NEULAND.NS","CAPLIPOINT.NS","SEQUENT.NS",
        "PIRAMALPHAR.NS","SYNGENE.NS","MAXHEALTH.NS","NARAYANA.NS","FORTIS.NS",
        "APOLLOHOSP.NS","ALEMBIC.NS","ZYDUSLIFE.NS"
    ],

    "CLUSTER_4": [  # FMCG
        "HINDUNILVR.NS","ITC.NS","NESTLEIND.NS","BRITANNIA.NS","DABUR.NS",
        "GODREJCP.NS","EMAMILTD.NS","COLPAL.NS","UBL.NS","PIDILITIND.NS",
        "TATACONSUM.NS","DABUR.NS","BRITANNIA.NS"
    ],

    "CLUSTER_5": [  # Auto / Mobility
        "MARUTI.NS","M&M.NS","TATAMOTORS.NS","EICHERMOT.NS","BAJAJ-AUTO.NS",
        "HEROMOTOCO.NS","ASHOKLEY.NS","TVSMOTOR.NS","BALKRISIND.NS",
        "BAJAJ-AUTO.NS","EICHERMOT.NS","HEROMOTOCO.NS"
    ],

    "CLUSTER_6": [  # Metals / Mining / Commodities
        "JSWSTEEL.NS","TATASTEEL.NS","HINDALCO.NS","COALINDIA.NS",
        "HINDCOPPER.NS","JINDALSAW.NS","RATNAMANI.NS","GMDC.NS",
        "GUJALKALI.NS","INDIAGLYCO.NS","DCW.NS","GRASIM.NS","HIMADRI.NS"
    ],

    "CLUSTER_7": [  # All other tickers not clearly in above clusters
        "RELIANCE.NS","LT.NS","BAJFINANCE.NS","BHARTIARTL.NS","NTPC.NS","POWERGRID.NS",
        "ADANIPORTS.NS","BAJAJFINSV.NS","ULTRACEMCO.NS","UPL.NS","HDFCLIFE.NS",
        "ASIANPAINT.NS","SHREECEM.NS","PIDILITIND.NS","HAVELLS.NS","BERGEPAINT.NS",
        "DLF.NS","ZEEL.NS","CHOLAFIN.NS","MPHASIS.NS","GAIL.NS","IOC.NS","PETRONET.NS",
        "REC.NS","PNBHOUSING.NS","ICICILOMBARD.NS","TATACONSUM.NS","OBEROIRLTY.NS",
        "PAGEIND.NS","PIIND.NS","COROMANDEL.NS","MANAPPURAM.NS","ALEMBIC.NS",
        "THERMAX.NS","SUNDARMFIN.NS","SHRIRAMFIN.NS","UBL.NS","IEX.NS","KEI.NS",
        "BLUESTARCO.NS","TRENT.NS","ADANIWIL.NS","ADANIPOWER.NS","GUJFLUORO.NS",
        "CASTROLIND.NS","INDHOTEL.NS","RADICO.NS","APLAPOLLO.NS","RELAXO.NS",
        "FINEORG.NS","HATSUN.NS","PRESTIGE.NS","OBEROIRLTY.NS","VARUNBEV.NS",
        "EMAMILTD.NS","IGL.NS","KAJARIACER.NS","RITES.NS","SKFINDIA.NS","HAL.NS",
        "CESC.NS","ENDURANCE.NS","GRINDWELL.NS","GNFC.NS","NAVINFLUOR.NS","LINDEINDIA.NS",
        "AIAENG.NS","KANSAINER.NS","BIRLASOFT.NS","COFORGE.NS","SYNGENE.NS","NARAYANA.NS",
        "FORTIS.NS","PVR.NS","INOXLEISUR.NS","SPANDANA.NS","CUB.NS","KVB.NS","SOUTHBANK.NS"
    ]
}

